# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_circles(object):
    def setupUi(self, circles):
        circles.setObjectName("circles")
        circles.resize(635, 478)
        self.btn = QtWidgets.QPushButton(parent=circles)
        self.btn.setGeometry(QtCore.QRect(280, 420, 93, 28))
        self.btn.setObjectName("btn")

        self.retranslateUi(circles)
        QtCore.QMetaObject.connectSlotsByName(circles)

    def retranslateUi(self, circles):
        _translate = QtCore.QCoreApplication.translate
        circles.setWindowTitle(_translate("circles", "Form"))
        self.btn.setText(_translate("circles", "кнопка"))
